version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:latest
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: login_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Redis缓存
  redis:
    image: redis:latest
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # 业务服务
  business-service:
    image: golang:latest
    container_name: business_service
    restart: unless-stopped
    ports:
      - "8081:8081"
    working_dir: /app
    volumes:
      - ./business:/app
    command: >
      sh -c "
      go env -w GOPROXY=https://goproxy.cn,direct &&
      go env -w GOSUMDB=sum.golang.google.cn &&
      go mod download &&
      go run main.go
      "
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GOSUMDB=sum.golang.google.cn
      - BUSINESS_PORT=8081
      - BUSINESS_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=login_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - SMS_ACCESS_KEY_ID=${SMS_ACCESS_KEY_ID}
      - SMS_ACCESS_KEY_SECRET=${SMS_ACCESS_KEY_SECRET}
      - SMS_SIGN_NAME=${SMS_SIGN_NAME}
      - SMS_TEMPLATE_CODE=${SMS_TEMPLATE_CODE}
      - SMS_REGION_ID=${SMS_REGION_ID}
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # 网关服务
  gateway-service:
    image: golang:latest
    container_name: gateway_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./gateway:/app
    command: >
      sh -c "
      go env -w GOPROXY=https://goproxy.cn,direct &&
      go env -w GOSUMDB=sum.golang.google.cn &&
      go mod download &&
      go run main.go
      "
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GOSUMDB=sum.golang.google.cn
      - GATEWAY_PORT=8080
      - GATEWAY_MODE=release
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_ACCESS_EXPIRE=900
      - JWT_REFRESH_EXPIRE=86400
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - BUSINESS_API_BASE_URL=http://business-service:8081
      - BUSINESS_API_TIMEOUT=30
    depends_on:
      - redis
      - business-service
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
